### ISSUE TITLE
Profile Page Functions

### ISSUE THREAD

**Issue by venkaa28** [atrusnak/Fingerpaint#12]
Clicking Change Username and Change Profile Picture do nothing. Clicking Change Password produces two text fields allowing me to enter my current password, and the password I would like to change my password to, however, after filling out the text fields, clicking submit does nothing. 

Severity: Medium

Suggestion:
If these features are not implemented yet, I recommend not including the buttons on your live deployment. If they are implemented, they are not functional on the live deployment.

**Comment by adamazmil** [comment]
Implemented Change Username and Change Profile Picture. That password behavior is an incorrect password behavior we have not implemented an error message yet.
